version: 1.0
backend: compose
defaults:
  group: group1
  project-name: sugar
groups:
  group1:
    project-name: sugar
    config-path: there-is-no-compose.yaml
    services:
      default: service1-1,service1-3
      available:
        - name: service1-1
        - name: service1-2
        - name: service1-3
