{% set name = "containers-sugar" %}
{% set version = "1.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/containers_sugar-{{ version }}.tar.gz
  sha256: 2e4b2796c2759f1453be7277590504321cef959f85a9adadc426481593d23b9d

build:
  entry_points:
    - sugar = sugar.__main__:run_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - __unix
    - python >=3.9,<3.13
    - jinja2 >=2
    - sh >=2.0.0
    - pyyaml >=6
    - colorama >=0.4.6
    - python-dotenv >=0.21.1
    - typer >=0.9.0
    - plotille >=5
    - rich >=10.11.0
    - textual >=0.48
    - docker-compose >=2,<3
test:
  imports:
    - sugar
  commands:
    # note: pip check fails because it expect compose-go, but that is just a wrapper to the 
    #       docker compose v2, and it is not available on conda-forge, because it is already 
    #       provided by docker-compose >=2.
    # - pip check
    - sugar --help
  requires:
    - pip

about:
  home: https://github.com/osl-incubator/containers-sugar
  summary: Simplify the usage of containers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felipepaes
    - xmnlab
