{% set name = "containers-sugar" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/containers_sugar-{{ version }}.tar.gz
  sha256: 90a659a91516e40081cf297fd0d4a54ba2366321092b0c0613b873b3ba529d0f

build:
  entry_points:
    - sugar = sugar.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4
    - poetry-core >=1.0.0
    - pip
  run:
    - __unix
    - python >=3.8.1,<4
    - jinja2 >=2
    - sh >=2.0.0
    - pyyaml >=6
    - colorama >=0.4.6
    - python-dotenv >=0.21.1
test:
  imports:
    - sugar
  commands:
    - pip check
    - sugar --help
  requires:
    - pip

about:
  home: https://github.com/osl-incubator/containers-sugar
  summary: Simplify the usage of containers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felipepaes
    - xmnlab
