{% set name = "containers-sugar" %}
{% set version = "1.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/containers_sugar-{{ version }}.tar.gz
  sha256: 857b925aa9c68318a59e506bd02c1b97c57628c73e021ff50cf904101f5ad141

build:
  entry_points:
    - sugar = sugar.__main__:run_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - __unix
    - python >={{ python_min }},<3.13
    - jinja2 >=2
    - sh >=2.0.0
    - pyyaml >=6
    - colorama >=0.4.6
    - python-dotenv >=0.21.1
    - typer >=0.9.0
    - plotille >=5
    - rich >=10.11.0
    - textual >=0.48
    - docker-compose >=2,<3
    - jsonschema >=4
    - xonsh >=0.15.0
test:
  files:
    - .sugar.yaml
  imports:
    - sugar
  # commands:
  #   note: pip check fails because it expect compose-go, but that is just a wrapper to the 
  #         docker compose v2, and it is not available on conda-forge, because it is already 
  #         provided by docker-compose >=2.
  #         sugar --help touches `docker` via sh lib, and it breaks the ci
  #   - pip check
  #   - sugar --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/osl-incubator/containers-sugar
  summary: Simplify the usage of containers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felipepaes
    - xmnlab
